### ISSUE TITLE
Probably a little bug

### ISSUE THREAD

**Issue by saltonz** [pisa-engine/taily#9]
For the file <taily.hpp>

At the definition of struct Feature_Statistics: 
Maybe
"std::size_t struct_size = 2 * sizeof(double) + sizeof(int);"
should be replaced with
"std::size_t struct_size = 2 * sizeof(double) + sizeof(std::int64_t);"

Which will lead to error of data loaded when reading Feature_Statistics from file.

**Comment by amallia** [comment]
@saltonz thanks, you are right!
